[package]
name = "linux-gopro-webcam-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
futures-util = "0.3"
futures-channel = "0.3"
netlink-packet-core = "0.9"
netlink-packet-route = "0.33"
netlink-sys = "0.9"
rtnetlink = "0.23"
tokio = { version = "1", features = ["macros", "net", "rt", "signal", "sync", "time"] }
tokio-udev = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
v4l = "0.14"
